version: '3.8'

services:
  fastapi-vscode-debug-setup:
    image: fastapi-vscode-debug-setup
    build:
      context: ./project
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn project.orders.app:app --host 0.0.0.0 --port 8000 --reload"]
    environment:
      - APP_MESSAGE=Hello debugger
    env_file:
      - .env
    ports:
      - 8000:8000
      - 5678:5678
