version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn orders.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .envs/.local/.fastapi
    depends_on:
      - web-db

  # new
  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - .envs/.local/.postgres
