version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn orders.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - .envs/.local/.fastapi
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - .envs/.local/.postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .envs/.local/.pgadmin
    ports:
      - 8080:80
    volumes:
      - admin-data:/var/lib/pgadmin

volumes:
  db-data:
  admin-data:
